language: python
sudo: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy3"
install:
  - "pip install ."
script:
  - "python example.py --value 10 -c :12 -w 9:"
  - "python setup.py test"
  - "python -m doctest README.md"
